### PR TITLE
Improve help mode

### PR DESCRIPTION
**Pull request by yangruihan**
Here are a few small optimizations:

1. Add tile code after tile emoji for displaying the information more clearly.

f86a19eaae4267bdf283506cde770c8

6ebe22c86528f9efbc1bbdf275a70b6

2. Reorganized action types, and how information is presented

- Accept: Call
- Accept: Call {argument}
- Decline: Call
- Riichi: {tile}
- Accept: Kita
- Accept: Kyuushu Kyuuhai
- Discard: {tile}

### CODE REVIEW

**Comment by dioarame** [comment]
Thanks for Improvement. But I can't get it ***.js patch version.
But at now, I think files are seperate so checking files is so hard for me. &-|
(Because I am beginner in Github..)
So, how can I get ***.js patch version in repository like before distribution?

**Comment by yangruihan** [comment]
> Thanks for Improvement. But I can't get it ***.js patch version. But at now, I think files are seperate so checking files is so hard for me. &-| (Because I am beginner in Github..) So, how can I get ***.js patch version in repository like before distribution?

You can find it [here](https://gist.github.com/yangruihan/3ae89420aabe92898c3e054c66a11663) temporarily, I think I might need to discuss with jim about how to publish the whole project. @Jimboom7

**Comment by dioarame** [comment]
@yangruihan Thanks for quick and tender reply!
I'm testing improvement now, and visibility is quite better than before.
I anticipate whole projects improvement version!

**Comment by yangruihan** [comment]
> > Thanks for Improvement. But I can't get it ***.js patch version. But at now, I think files are seperate so checking files is so hard for me. &-| (Because I am beginner in Github..) So, how can I get ***.js patch version in repository like before distribution?
> 
> You can find it [here](https://gist.github.com/yangruihan/3ae89420aabe92898c3e054c66a11663) temporarily, I think I might need to discuss with jim about how to publish the whole project. @Jimboom7

I added a Github Action to solve this problem, please see https://github.com/Jimboom7/AlphaJong/pull/51 for more detail.

**Comment by ayssia** [comment]
我自己改动了一点东西，help模式下会直接给bot要打的牌染色，供参考：

`function callDiscard(tileNumber) {
	if (MODE === AIMODE.AUTO) {
		view.DesktopMgr.Inst.players[0]._choose_pai = view.DesktopMgr.Inst.players[0].hand[tileNumber];
		view.DesktopMgr.Inst.players[0].DoDiscardTile();
	} else {
		let tileID = ownHand[tileNumber];
		let tileName = getTileName(tileID, false);
		showCrtStrategyMsg(`discard ${tileName};`);
		view.DesktopMgr.Inst.mainrole.hand.forEach(tile => tile.val.toString() == tileID ? tile._SetColor(new Laya.Vector4(0.5, 0.8, 0.9, 1)) : tile._SetColor(new Laya.Vector4(1, 1, 1, 1)));
	}
}`

**Pull request merged**
