### PR TITLE
AI-Core Rework

### PR DESCRIPTION
**Pull request by Jimboom7**
This is basically a whole rework of the core AI.
It seems to be running stable now (no bugs that cause the bot to crash), **BUT** it is by far not optimized yet.
Changing the old system to using the above values means that all the stuff that had been carefully finetuned before now needs to be looked at again in detail. The easiest way to do so is to let the bot play some games and watch out for moves that appear to be wrong or not optimal.
At the moment I assume the AI is equal or even slightly worse than the old AI, but after some fixes and finetuning it should become much stronger (Maybe Jade Room level).

### What is new?

- Exact shanten calculation
- Estimated hand value for own hand
- Estimated hand value for opponents hands
- More accurate estimation whether opponents are tenpai or not (Tenpai %)
- More accurate estimation whether a tile deals in or not (Deal In %)

With the above data it should be possible for the bot to make better decisions, especially in regards to Push/Fold or calling Riichi.

### How to test it

Download the new version [here](https://github.com/Jimboom7/AlphaJong/files/8682126/AlphaJong_1.3.0.user-beta.zip). It would be very helpful if you report any problems or bugs that occur!
Please use this PR for any feedback or bug reports. It would be great if you could include the log of the problematic turn (including the debug string) and/or a screenshot.

_**Currently known problems:**_
- ~~Parameters (Like EFFICIENCY_VALUE) have no effect yet, I'm still looking for a good way to integrate them.~~
- ~~Sometimes the bot calls pon or chi when there is high danger and it should already be folding.~~

**_Related Issues:_**
#36 #45 (Should improve some of the points mentioned there)

### CODE REVIEW

**Comment by yangruihan** [comment]
Feedback report: https://github.com/Jimboom7/AlphaJong/issues/45#issuecomment-1119204731

**Comment by yangruihan** [comment]
Feedback report: https://github.com/Jimboom7/AlphaJong/issues/45#issuecomment-1119255482

**Comment by Jimboom7** [comment]
After fixing a lot of bugs and finetuning some values I now feel like this version is definitely stronger than the old one. I'll continue to test it for some time, but I don't think I need to make any more big changes.
If anyone wants to try it out now here is the latest build. Feedback is welcome: [AlphaJong_1.3.0-experimental.user.zip](https://github.com/Jimboom7/AlphaJong/files/8665153/AlphaJong_1.3.0-experimental.user.zip)

**Comment by Jimboom7** [comment]
This branch is now ready for release. I'll wait a few more days before merging and publishing it as 1.3.0, in case anyone finds major bugs or problems. Here is the beta for now: [AlphaJong_1.3.0.user-beta.zip](https://github.com/Jimboom7/AlphaJong/files/8682126/AlphaJong_1.3.0.user-beta.zip)

**Comment by dioarame** [comment]
> This branch is now ready for release. I'll wait a few more days before merging and publishing it as 1.3.0, in case anyone finds major bugs or problems. Here is the beta for now: [AlphaJong_1.3.0.user-beta.zip](https://github.com/Jimboom7/AlphaJong/files/8682126/AlphaJong_1.3.0.user-beta.zip)

Thank you for the update.
However, I leave a question because there is a confusing part of the note in the script.

It is about the figure of PERFORMANCE_MODE, so please check if what I understand is correct.

* * Range 0 to 4. Decrease calculation time at the cost of efficiency (2 equals the time of ai version 1.2.1 and before).
* * 0 = Highest Precision and Calculation Time. 4 = Lowest Precision and Calculation Time.

Is it correct that 0 in the range of the figures is accompanied by a long time and precision? Because when I compared 4 and 0 in my environment, I thought that 0 was the opposite because it worked smoother and faster.

If it was a foolish question, I would like you to answer it with an emoji. :)

**Comment by ms860309** [comment]
I find that this version often seems to discard the triplets (kotsu) of jihai (honor).
These jihai can contribute yaku so i think there is no reason to discard them.

> This branch is now ready for release. I'll wait a few more days before merging and publishing it as 1.3.0, in case anyone finds major bugs or problems. Here is the beta for now: [AlphaJong_1.3.0.user-beta.zip](https://github.com/Jimboom7/AlphaJong/files/8682126/AlphaJong_1.3.0.user-beta.zip)

**Comment by Jimboom7** [comment]
> Is it correct that 0 in the range of the figures is accompanied by a long time and precision? Because when I compared 4 and 0 in my environment, I thought that 0 was the opposite because it worked smoother and faster.

You are correct, I mixed it up. Thanks for pointing it out, it's fixed now!

> I find that this version often seems to discard the triplets (kotsu) of jihai (honor).
These jihai can contribute yaku so i think there is no reason to discard them.

That should only be the case when it's too dangerous and the bot goes into fold (betaori) mode. If the playstyle is too defensive you can try lowering the `SAFETY` parameter.
Besides that the parameters SAKIGIRI and KEEP_SAFETILE are also related to honor tiles and will make the bot try to keep them.

**Pull request merged**
